// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHc7bnvor-Jq8ci_lS_zWZg4PjGE8LJmw',
    appId: '1:944835113141:web:999df64e892a22b69d0efc',
    messagingSenderId: '944835113141',
    projectId: 'proyectomovil-4b36b',
    authDomain: 'proyectomovil-4b36b.firebaseapp.com',
    databaseURL: 'https://proyectomovil-4b36b-default-rtdb.firebaseio.com',
    storageBucket: 'proyectomovil-4b36b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZtFfaRuYa_-bNwV3X2GbDMJ3MugTpdxo',
    appId: '1:944835113141:android:deb7c35ec604acdf9d0efc',
    messagingSenderId: '944835113141',
    projectId: 'proyectomovil-4b36b',
    databaseURL: 'https://proyectomovil-4b36b-default-rtdb.firebaseio.com',
    storageBucket: 'proyectomovil-4b36b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSGtUERosBLUbvOMnwJ85UbrBkrUNBy4k',
    appId: '1:944835113141:ios:7d3d40258a06dfc39d0efc',
    messagingSenderId: '944835113141',
    projectId: 'proyectomovil-4b36b',
    databaseURL: 'https://proyectomovil-4b36b-default-rtdb.firebaseio.com',
    storageBucket: 'proyectomovil-4b36b.appspot.com',
    iosClientId: '944835113141-202ii583blmmhu4qcr5lh4lma3ceehrl.apps.googleusercontent.com',
    iosBundleId: 'com.example.bicycle',
  );
}
